Runner (and backend) improvements
IPDSnelting/velcom pull request #59
Opened 2020-09-12 18:18 UTC by Garmelon

- Fix bench repo tar creation in backend
- Move some utility classes to shared so runner can use them
- Unify status and benchmark failure formatting
- Use correct and properly formatted system info
- Do runner-side websocket ping pong

There appear to still be some issues with pings sometimes timing out and the backend not being able to properly transmit tars to the runner. Until those are fixed, I'm going to leave this PR in draft stage.

2020-09-12 20:11 UTC, Garmelon commented
This seems to have fixed the timeout and tar issues, which means that this PR should be ready for merging.

2020-09-12 20:19 UTC, I-Al-Istannen approved these changes

2020-09-12 22:13 UTC, Garmelon commented
Further changes:
- Backend properly tars bench repo again
- No more timeouts while sending repos to runner
- Improved `/queue` endpoint performance

2020-09-12 22:19 UTC, I-Al-Istannen approved these changes

2020-09-17 16:51 UTC, kwerber requested changes

2020-09-17 16:51 UTC, kwerber commented on backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/CommitReadAccess.java
> +			return new HashMap<>();
Hier eventuell [Collections.emptyMap()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Collections.html#emptyMap()) ?

2020-09-17 17:11 UTC, kwerber approved these changes

2020-09-17 17:11 UTC, merged